import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { readXls } from "../src/index";
import type { Cell } from "../src/index";

// Integration coverage over a corpus of synthetic-but-realistic BIFF8 files,
// each targeting a reader behavior the single sample.xls didn't exercise: the
// 1900/1904 date systems, CONTINUE-split shared strings, wide (unicode) strings,
// numeric encodings, and a larger grid. All fixtures are generated by
// test/fixtures/generate.py — see test/fixtures/README.md.

function firstSheetRows(name: string): readonly (readonly Cell[])[] {
  const bytes = new Uint8Array(readFileSync(new URL(`./fixtures/${name}`, import.meta.url)));
  const sheet = readXls(bytes).sheets[0];
  if (!sheet) throw new Error(`${name}: no first sheet`);
  return sheet.rows;
}

// Reads cell (row, col) and asserts it's a Date, returning its UTC ISO string.
function isoAt(rows: readonly (readonly Cell[])[], row: number, col: number): string {
  const value = rows[row]?.[col];
  expect(value).toBeInstanceOf(Date);
  return (value as Date).toISOString();
}

describe("date systems (1900 vs 1904)", () => {
  it("decodes the 1900-epoch workbook", () => {
    const rows = firstSheetRows("dates-1900.xls");
    expect(isoAt(rows, 0, 0)).toBe("2024-04-02T00:00:00.000Z");
    expect(isoAt(rows, 1, 0)).toBe("1999-12-31T00:00:00.000Z");
  });

  it("decodes the 1904-epoch workbook to the same wall-clock dates", () => {
    // The whole point of the 1904 flag: the same calendar date must come back
    // identically, even though the stored serial differs by 1462 days.
    const rows = firstSheetRows("dates-1904.xls");
    expect(isoAt(rows, 0, 0)).toBe("2024-04-02T00:00:00.000Z");
    expect(isoAt(rows, 1, 0)).toBe("1999-12-31T00:00:00.000Z");
  });

  it("decodes a time-of-day value's clock portion", () => {
    // A pure time has a different date part per epoch (that's expected), but the
    // 13:30:00 clock time must be preserved in both.
    expect(isoAt(firstSheetRows("dates-1900.xls"), 2, 0)).toContain("13:30:00");
    expect(isoAt(firstSheetRows("dates-1904.xls"), 2, 0)).toContain("13:30:00");
  });
});

describe("shared strings", () => {
  it("reassembles a string split across CONTINUE records", () => {
    const rows = firstSheetRows("continued-string.xls");
    expect(rows[0]?.[0]).toBe("A".repeat(9000));
    expect(rows[1]?.[0]).toBe("short-after-long");
  });

  it("shares one SST entry between cells with the same text", () => {
    const rows = firstSheetRows("continued-string.xls");
    expect(rows[2]?.[0]).toBe("REPEAT");
    expect(rows[3]?.[0]).toBe("REPEAT");
  });
});

describe("unicode (wide) strings", () => {
  it("decodes non-ASCII text via the 16-bit string path", () => {
    const rows = firstSheetRows("unicode.xls");
    expect(rows[0]?.[0]).toBe("Ações");
    expect(rows[1]?.[0]).toBe("café ☕");
    expect(rows[2]?.[0]).toBe("日本語");
    expect(rows[3]?.[0]).toBe("Ω≈ç√");
  });
});

describe("numeric encodings", () => {
  it("decodes integers, negatives, decimals, and large magnitudes", () => {
    const rows = firstSheetRows("numbers.xls");
    const values = rows.map((r) => r[0]);
    expect(values).toEqual([0, 1, -1, 42, -273.15, 3.14159, 1000000, 0.0001, 2500000000]);
  });
});

describe("larger grid", () => {
  it("reads a full 200x20 dense grid with correct values", () => {
    const rows = firstSheetRows("large-grid.xls");
    expect(rows).toHaveLength(200);
    expect(rows[0]).toHaveLength(20);
    expect(rows[0]?.[0]).toBe(0);
    expect(rows[199]?.[19]).toBe(199 * 100 + 19);
    expect(rows[137]?.[8]).toBe(137 * 100 + 8);
  });
});
