import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { readFirstSheet, readXls, XlsError } from "../src/index";

// A real BIFF8 workbook generated by Python's xlwt (Excel 97-2003 format),
// exercising shared strings, ints, floats (via RK), a date-formatted number, and
// booleans across two sheets. See test/fixtures/README.
const sample = new Uint8Array(readFileSync(new URL("./fixtures/sample.xls", import.meta.url)));

describe("readXls (integration on a real .xls)", () => {
  it("returns every sheet in file order", () => {
    expect(readXls(sample).sheets.map((sheet) => sheet.name)).toEqual(["Types", "Renda Fixa"]);
  });

  it("decodes shared strings, integers and floats", () => {
    const types = readXls(sample).sheets[0];
    expect(types?.rows[0]).toEqual(["Emitente", "Taxa", "Data"]);
    expect(types?.rows[1]).toEqual(["BANCO X S/A", 1.1, 42]);
  });

  it("decodes booleans and negative/decimal numbers", () => {
    const types = readXls(sample).sheets[0];
    expect(types?.rows[3]).toEqual([true, -5, 3.14]);
  });

  it("converts a date-formatted number into a Date", () => {
    const date = readXls(sample).sheets[0]?.rows[2]?.[2];
    expect(date).toBeInstanceOf(Date);
    expect((date as Date).toISOString().slice(0, 10)).toBe("2024-04-02");
  });

  it("reads a non-first sheet in full", () => {
    const rendaFixa = readXls(sample).sheets[1];
    expect(rendaFixa?.name).toBe("Renda Fixa");
    expect(rendaFixa?.rows[1]).toEqual(["CDB DI", 267.85]);
  });

  it("readFirstSheet returns the first worksheet", () => {
    expect(readFirstSheet(sample)?.name).toBe("Types");
  });

  it("throws XlsError when the bytes are not an OLE2 container", () => {
    expect(() => readXls(new Uint8Array([1, 2, 3, 4]))).toThrow(XlsError);
  });
});
